#!/bin/bash

## Author :	Maki
## Contact : alan.marrec@protonmail.com

# Colors management
NC='\033[0m' # No color
RED='\033[0;31m'
LRED='\033[1;31m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
BLUE='\033[1;34m'
GRAY='\033[1;37m'

# Argument management
#function Usage() {
usage="$(basename "$0") [-h] [-d <dump_name>] [-f <folder_name>] [-p <vol_plugin_path>] [-a <volume_path>] -- Script that performs basic volatility command and stores them into a directory

where:
	-h	Show this help
	-d 	Name of the memory dump to analyze
	-f	Name of the folder
	-p  Volatility plugins path
	-a 	Volume path (if a volume has to be mount)

Examples : 

./auto_vol -d /home/maki/memory.raw -f /home/maki/tests -p /home/maki/zTools/plug_vol
./auto_vol -d /home/maki/memory.raw -f /home/maki/tests -p /home/maki/zTools/plug_vol -a /home/maki/image.dd"

while getopts "hd:f" optionName; do
	case "$optionName" in
		h)	printf "$usage" 
			exit ;;
		d)	dump=$2;;
		f)	base=$4;;
		p)  plug=$6;;
		a)	disc=$8;;
		[?])	echo "Wrong argument, please see the help page (-h)" 
			exit 1;;
	esac
done

#}

# Windows operations
function Windows() {
	Arbo

	OS="$(volatility -f ${dump} imageinfo 2> /dev/null | while read line; do if [[ "$line" =~ "Suggested" ]]; then echo "$line" | awk '{print $4}' | sed -e 's/,//g'; fi; done)"
	printf "[+] ${GREEN}OS Type${NC} : ${OS}\n" | tee -a ${base}/audit.txt

	# Get the name of the computer
	name="$(strings ${dump} | grep "^COMPUTERNAME" | head -n 1 | awk '{split($0,a,"="); print a[2]}')"
	printf "[+] ${GREEN}Computer name${NC} : ${name}\n" | tee -a ${base}/audit.txt

	# Get users hash
	hashd="$(volatility -f ${dump} --profile="${OS}" hashdump 2> /dev/null)"
	if [[ $? != 0 ]]; then
		printf "[-] ${RED}No users${NC} hash found.\n"
	else
		printf "[+] ${GREEN}Credentials${NC}\n"
		printf "${hashd}\n" > ${base}/hash.txt
		while read hashd; 
		do
			users=$(echo ${hashd} | cut -f1 -d":")
			plop=$(echo ${hashd} | sed 's/://g' | grep -o '.\{32\}$')
			decrypt=$(curl --data "hash=${plop}&decrypt=Décrypter" -s http://md5decrypt.net/Ntlm/ | sed 's/<[^>]*>//g' | grep ${plop} | awk '{print $3}' | sed 's/.\{6\}$//g')
			printf "${users} : ${decrypt}\n"
		done < ${base}/hash.txt
		printf "\n[+] Complete ${GREEN}hashdump${NC} in ${RED}${base}/hash.txt${NC}\n"
	fi

	# Get command
	cmdsc="$(volatility -f ${dump} --profile="${OS}" cmdscan 2> /dev/null)"
	printf "\n\nCommand scan : ${cmdscan}\n" >> ${base}/audit.txt

	# Get consoles command
	conso="$(volatility -f ${dump} --profile="${OS}" consoles 2> /dev/null)"
	printf "\nConsoles : " >> ${base}/audit.txt
	echo "${conso}" >> ${base}/audit.txt  # Illegal characters, printf failed
	printf "[+] Consoles commands recovery ${GREEN}done${NC} !\n"

	# Dump pstree in current_process.txt locate in ${base} directory
	volatility -f ${dump} --profile="${OS}" pstree 2> /dev/null >> ${base}/current_process.txt

	# Get all process, even hidden ones (not in a tree)
	volatility -f ${dump} --profile="${OS}" psxview 2> /dev/null >> ${base}/all_process.txt

	# Clipboard paste in audit.txt
	clip="$(volatility -f ${dump} --profile="${OS}" clipboard 2> /dev/null)"
	echo "\nClipboard : ${clip}" >> ${base}/audit.txt
	printf "[+] Clipboard recovery ${GREEN}done${NC} !\n"

	printf "[+] File ${RED}${PWD}/${base}/audit.txt${NC} is ${GREEN}completed${NC}.\n"

	# Get screenshot from the ${dump}
	mkdir ${base}/screenshot
	volatility -f ${dump} --profile="${OS}" screenshot -D ${base}/screenshot/ &> /dev/null
	printf "[+] Screenshot recovery ${GREEN}done${NC} !\n"

	# Do a scan of present files in the ${dump}
	volatility -f ${dump} --profile="${OS}" filescan > ${base}/present_file.txt 2> /dev/null
	printf "[+] Filescan ${GREEN}done${NC} !\n"

	# Get history from ${dump}
	volatility -f ${dump} --profile="${OS}" iehistory > ${base}/iehistory.txt 2> /dev/null
	printf "[+] Internet history recovery ${GREEN}done${NC} !\n"

	# Get network traffic
	volatility -f ${dump} --profile="${OS}" netscan > ${base}/netscan.txt 2> /dev/null
	printf "[+] Network analysis ${GREEN}done${NC} !\n"

	# Looking for encrypted volumes
	# $1 = First parameter of the Windows function, plugin_path
	BitlockDetection $1 $2
	TruecryptDetection

	FinalCmds
}

function BitlockDetection() {
	# Is bitlocker present ? If yes, see tools associate
	if [[ $(cat ${base}/all_process.txt | grep -i "fvenotify") ]]; then
	    printf "[+] Bitlocker ${GREEN}found${NC} !\n"
	    bdefind=1
	    echo "Bitlocker is present on the volume" >> ${base}/audit.txt
	    volatility --plugins="$1" -f ${dump} --profile="${OS}" bitlocker 2> /dev/null | tee ${base}/bitlocker_infos.txt
    	a1=$(fdisk -l "$2" | tail -n 1 | awk '{print $2}')
    	a2=$(fdisk -l "$2" | sed '1d' | head -n 1 | awk '{print $6}')
    	bitlockKey=$(volatility --plugins="$1" -f ${dump} --profile="${OS}" bitlocker 2> /dev/null | head -n-1  | tail -n 2 | awk '{print $3}' | tr '\n' ':' | sed 's/.$//g')
    	mkdir ${base}/bitlock_tmp 2> /dev/null
    	mkdir /mnt/tmp 2> /dev/null
    	bdemount -X allow_root -k ${bitlockKey} -o $((${a1}*${a2})) "$2" /mnt/tmp 
    	bdefs=$(ls /mnt/tmp | head -n 1)
    	mount -o loop,ro /mnt/tmp/${bdefs} ${base}/bitlock_tmp
    	tree ${base}/bitlock_tmp
	fi
}

function TruecryptDetection() {
	# Is truecrypt present ? If yes, informations stored in truecrypt_info.txt
	if [[ $(cat ${base}/all_process.txt | grep -i "truecrypt") ]]; then
		printf "[+] Truecrypt ${GREEN}found${NC} !\n"
		touch ${base}/truecrypt_info.txt
		echo "Truecrypt summary : " >> ${base}/truecrypt_info.txt
		volatility -f ${dump} --profile="${OS}" truecryptsummary 2> /dev/null >> ${base}/truecrypt_info.txt
		printf "\nPassphrase : " >> ${base}/truecrypt_info.txt
		TCPassphrase=$(volatility -f ${dump} --profile="${OS}" truecryptpassphrase 2> /dev/null | awk '{print $NF}')
		echo ${TCPassphrase} >> ${base}/truecrypt_info.txt
		printf "${PURPLE}[+] Truecrypt passphrase${NC} : ${TCPassphrase}\n"
		printf "[+] Complete results are stored in : ${RED}${PWD}/${base}/truecrypt_info.txt${NC}\n"
		printf "Actually this script cannot find truecrypt volume...\nYou can mount it with those following commands ${RED}as root${NC} :\n"
		printf "# losetup /dev/loop0 /path/to/truecrypt.file\n# cryptsetup --type tcrypt open /dev/loop0 myContainer\n# mount /dev/mapper/myContainer /mnt/tmp_tc\nMore informations at : http://www.adercon.com/ac/node/114"
	fi
}

# Linux operations
function Linux() {
	Arbo

	printf "[+] Raw data about Linux version :\n" > ${base}/audit.txt
	linvers=$(strings ${dump} | grep -i "Linux version" | uniq) 
	bootimg=$(strings ${dump} | grep -ioE 'BOOT_IMAGE\S+' | uniq) 
	printf "${linvers} \n$bootimg \n\n" >> ${base}/audit.txt

	# Is Ubuntu ?
	if [[ $(echo ${linvers} | grep -i ubuntu) ]]; then
		kernel_version=$(echo ${linvers} | awk '{print $3}')
		ubuntu_ver=$(echo ${linvers} | awk '{print $10}' | sed -n -e 's/^.*~//p' | sed -e 's/.\{3\}$//g')
		vagBoxType=$(./BoxNameParser.py $(echo ${ubuntu_ver}))
	fi

	printf "[!] Kernel version : ${kernel_version} \n" | tee -a ${base}/audit.txt
	printf "[!] Linux type : ${ubuntu_ver} \n" | tee -a ${base}/audit.txt
	printf "[!] Vagrant box : ${vagBoxType} \n\n" | tee -a ${base}/audit.txt

	mkdir ${base}/Vagrant_dir
	cd ${base}/Vagrant_dir

	vagrant init "${vagBoxType}" &> /dev/null
	printf "[+] Vagrant box ${GREEN}successfully added${NC} !\n"

	vagrant up &> /dev/null
	printf "[+] Vagrant box ${GREEN}up${NC} !\n"
	printf "[!] ${LRED}Waiting for SSH connection...${NC}\n"
	sleep 20
	
	vagrant ssh -c "sudo mkdir /profile && sudo chmod -R 777 /profile" &> /dev/null
	echo "[+] /profile folder created."
	
	vagrant scp ../../LinuxProfileGenerator.sh default:~ &> /dev/null
	printf "[+] ${GREEN}LinuxProfileGenerator.sh script${NC} copied in ${RED}user home${NC}\n"
	
	vagrant ssh -c "chmod +x ~/LinuxProfileGenerator.sh && sudo ~/LinuxProfileGenerator.sh ${kernel_version}"
	echo "[*] Kernel updated."
	sleep 25
	vagrant ssh -c "sudo ~/LinuxProfileGenerator.sh ${kernel_version}"
	printf "[+] Profil ${GREEN}created${NC}.\n"

	profPath=$(locate volatility/plugins/overlays/linux | head -n 1)
	newProfile=$(vagrant ssh -c "ls /profile") 2> /dev/null
	vagrant scp default:/profile/\* .  2> /dev/null
	printf "[+] ${GREEN}Profile imported${NC} from vagrant box !\n"

	# Vagrant scp is adding a char -> \r to the filename
	newProfile=$(echo $newProfile | sed 's/.\{1\}$//g')
	mv $newProfile ${profPath}
	printf "[+] ${GREEN}Profile paste${NC} in your : ${RED}${profPath}${NC}\n"

	vagrant destroy -f &> /dev/null
	printf "[+] Vagrant box ${GREEN}successfully destroyed${NC} !\n"

	# Back to the main directory
	cd ../..

	# Profile name parsing
	finalProfil=$(volatility --info | grep "$(echo $newProfile| sed -e 's/.\{4\}$//g')" | awk '{print $1}' 2> /dev/null)
	printf "\n\n[!] Linux banner : \n" | tee -a ${base}/audit.txt
	volatility -f ${dump} --profile=${finalProfil} linux_banner 2> /dev/null | tee -a ${base}/audit.txt

	volatility -f ${dump} --profile=${finalProfil} linux_pslist > ${base}/linux_pslist 2> /dev/null
	printf "[+] Process list ${GREEN}dump${NC} in ${RED}${base}/linux_pslist${NC}\n"

	volatility -f ${dump} --profile=${finalProfil} linux_psaux > ${base}/linux_pslist 2> /dev/null
	printf "[+] ${ps aux} command results ${GREEN}dump${NC} in ${RED}${base}/linux_psaux${NC}\n"

	volatility -f ${dump} --profile=${finalProfil} linux_pstree > ${base}/linux_pstree 2> /dev/null
	printf "[+] Process list tree is ${GREEN}dump${NC} in ${RED}${base}/linux_pstree${NC}\n"

	volatility -f ${dump} --profile=${finalProfil} linux_psxview > ${base}/linux_psxview 2> /dev/null
	printf "[+] Complete process list ${GREEN}dump${NC} in ${RED}${base}/linux_psxview${NC}\n"

	volatility -f ${dump} --profile=${finalProfil} linux_lsof > ${base}/linux_lsof 2> /dev/null
	printf "[+] List of opened file ${GREEN}dump${NC} in ${RED}${base}/linux_lsof${NC}\n"

	printf "\nCommand history : \n" >> ${base}/audit.txt
	volatility -f ${dump} --profile=${finalProfil} linux_bash >> ${base}/audit.txt 2> /dev/null
	printf "[+] Command history ${GREEN}dump${NC} in ${RED}${base}/audit.txt${NC}\n"

	volatility -f ${dump} --profile=${finalProfil} linux_lsmod > ${base}/linux_lsmod
	printf "[+] Kernel module list ${GREEN}dump${NC} in ${RED}${base}/linux_lsmod${NC}\n"

	printf "\nChecking TTY : \n" >> ${base}/audit.txt
	volatility -f ${dump} --profile=${finalProfil} linux_check_tty >> ${base}/audit.txt
	printf "[+] Check for every opened TTY ${GREEN}dump${NC} in ${RED}${base}/audit.txt${NC}\n"

	mkdir ${base}/network

	volatility -f ${dump} --profile=${finalProfil} linux_arp > ${base}/network/linux_arp
	printf "[+] ARP table ${GREEN}dump${NC} in ${RED}${base}/network/linux_arp${NC}\n"

	volatility -f ${dump} --profile=${finalProfil} linux_ifconfig > ${base}/network/linux_ifconfig
	printf "[+] ${PURPLE}ifconfig${NC} output ${GREEN}dump${NC} in ${RED}${base}/network/linux_ifconfig${NC}\n"

	mkdir ${base}/hardware

	printf "\nCPU Info : "
	volatility -f ${dump} --profile=${finalProfil} linux_cpuinfo >> ${base}/audit.txt
	printf "[+] CPU info ${GREEN}dump${NC} in ${RED}${base}/audit.txt${NC}\n"

	volatility -f ${dump} --profile=${finalProfil} linux_dmesg > ${base}/hardware/linux_dmesg
	printf "[+] ${PURPLE}dmesg${NC} output ${GREEN}dump${NC} in ${RED}${base}/hardware/linux_dmesg${NC}\n"

	volatility -f ${dump} --profile=${finalProfil} linux_mount > ${base}/linux_mount
	printf "[+] List mounted volume ${GREEN}dump${NC} in ${RED}${base}/linux_mount${NC}\n"







	

	
	

	


	# volatility --info | grep Linux 

	# echo ""
	# printf "${PURPLE}Actual profiles installed : ${NC}"
	# echo ""
	# volatility --info 2>&1 | grep -i 'profile for linux' 
	# echo ""
	# echo "Which profiles are you wanting to use ?"
	# read linProfile
	# #echo $linProfile # Debug
	# if [[ $(volatility -f ${dump} --profile=${linProfile} linux_banner 2>&1 | grep 'Linux version') ]]; then
	# 	printf "${GREEN}[+] Good profile"

	# 	if [[ $(strings ${dump} | grep -i "type=\"crypto_LUKS\"") ]]; then
	# 		printf ", crypto_LUKS find ! Trying to get the Master Key...${NC}\n"
	# 		./aeskeyfind ${dump} > ${base}/key.bin
	# 		printf "[+] Master Key stored in ${CYAN}key.bin${NC} !\n"
	# 		printf "${PURPLE}Would you like to mount a volume ? [Y/n]\n${NC}"
	# 		read input
	# 		if [[ $input == "Y" || $input == "y" ]]; then
	# 		        echo "Enter the volume path : "
	# 		        read volLin
	# 		        mkdir ${base}/lin_vol 2>&1
	# 		        cryptsetup --master-key-file key.bin luksOpen ${volLin} vol_lin
	# 		        mount /dev/mapper/vol_lin ${base}/lin_vol 
	# 		        chown ${USER}:users -R ${base}/lin_vol 
	# 		        printf "${GREEN}[+] Volume successfully mounted${NC}"
	# 		else
	# 		        echo "false"
	# 		fi
	# 	else
	# 		printf "\n${RED}[-] No LUKS type found in the dump${NC}"
	# 	fi

	# 	linBanner=$(volatility -f ${dump} --profile=${linProfile} linux_banner 2>&1)
	# 	echo $linBanner > ${base}/audit.txt


	# else
	# 	printf "${RED}Bad profile.. Try again :(${NC}"
	# 	exit
	# fi

	FinalCmds
}

function Requirement() {
	printf "Check for required packages.\n"
	commands_req=( "volatility" "bdemount (libbde-git)" "curl" "vagrant" "foremost" )
	for i in "${commands_req[@]}"; do
		printf "$i... "
		if [[ $(command -v $i) ]]; then
			printf "${GREEN}installed${NC}\n"
		else
			printf "${RED}not installed${NC}\n"
			flag_exit="1"
		fi	
	done

	if [[ $(vagrant plugin list | grep "scp" | awk '{print $1}') ]]; then
		printf "vagrant-scp... ${GREEN}installed${NC}\n"
	else
		printf "vagrant-scp... ${RED}not installed${NC}\n"
		printf "Run as ${LRED}root${NC} : vagrant plugin install vagrant-scp\n"
	fi

	if [[ $(locate bitlocker.py | head -n 1) ]]; then
		printf "bitlocker plugin... ${GREEN}installed${NC}\n"
	else
		printf "bitlocker plugin... ${RED}not installed${NC}\n"
		printf "Run as ${LRED}root${NC} : vagrant plugin install vagrant-scp\n"
	fi

}

function Arbo() {
	# Make the ${base} directory and audit.txt into ${base}
	mkdir ${base} 2> /dev/null
	touch ${base}/audit.txt

	printf "${BLUE}Common volatility commands are performing${NC}\nResulats in ${RED}${PWD}/${base}/audit.txt${NC}.\n"
	echo "Please wait..."
}

function FinalCmds() {
	# Do a foremost to recover some hidden files
	# printf "\n\n${CYAN}Foremost in progress..${NC}\n"
	# mkdir ${base}/foremost
	# foremost -i ${dump} -o ${base}/foremost >> /dev/null

	if [[ ${bdefind} ]]; then
		printf "Don't forget to unmout your bitlocker volume ;-)\numount /mnt/tmp/\numount -l ${base}/bitlock_tmp"
	fi
}

Requirement
if [[ $# == 0 ]]; then
	printf "${RED}Use -h argument for help${NC}"
elif [[ $(strings ${dump} | grep -i "Linux version") ]]; then
	Linux
else
	# Sixth parameter, the plugin path
	Windows "$6" "$8"
fi